name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  DEFAULT_PYTHON: "3.12"

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@4.2.2
        with:
          fetch-depth: 0

      - name: Fetch Existing Tags
        run: git fetch --force --tags

      - name: Parse Release Version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: python3 -m pip install --upgrade pip setuptools wheel pre-commit poetry

      - name: Install dev packages via poetry
        run: poetry install --with dev

      - name: Build package via poetry
        run: poetry build

      - name: Publish Draft Release
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ steps.version.outputs.version }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Dist to GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} dist/* --repo ${{ github.repository }}
